### ISSUE TITLE
Buffalo fix issues

### ISSUE THREAD

**Issue by fasmat** [gobuffalo/cli#104] opened 2022-01-13 14:38 UTC
### Description

There are several issues currently present in buffalo fix that I collect in this issue.

### Steps to Reproduce the Problem

  Please describe in painful detail what you did (so others can play along with you) to get to this point. This includes things like the exact command(s) you used, or the `curl` command you used, that sort of thing.

  1. Call `buffalo fix` on a pre 0.18.x gobuffalo code base
  2. Confirm that `buffalo fix` is allowed to do changes

### Expected Behavior

All incompatibilities with pre 0.18.x code are updated to the current version of buffalo

### Actual Behavior

The following short comings I have identified so far:

- [x] **Fix is slow**: When scanning for files buffalo fix seems to scan ALL files instead of just `*.go` files. With a large `node_module` folder fix becomes very slow.
- [x] **Fix fails to read files in `.git` folder**: Fix shouldn't even look at the `.git` folder
- [ ] **Code isn't updated**: It seems code and unit tests in generated resources are not all updated when calling `buffalo fix`
- [ ] **`buffalo-plugins.toml` not updated**: The link to the buffalo-pop plugin is still incorrect after running `buffalo fix`.
- [ ] **`buffalo test` doesn't install plugins any more**: Calling `buffalo test` used to automatically install any missing plugins in 0.17.x. This doesn't seem to be the case any more in 0.18.x requiring the user to manually install necessary plugins.

**Comment by sio4** [comment] 2022-03-15 10:02
I think the first two issues are the same issue I faced recently #116, and it was fixed by [1] and [2]. Please take a look at them if the issue is the same. I marked them as fixed.

For the others, could you please add some more information about them? Or are there separate issues for them?

[1] https://github.com/gobuffalo/genny/pull/44 - quick and dirty implementation of selective fs
[2] #121 - fixed "too many open files" error of fixer with except-fs

**Comment by paganotoni** [comment] 2022-04-07 12:53
Hey Folks! Is there any help I could give on this one? Regards

**Closed** 2022-06-20 03:05 UTC
Labels: no-issue-activity
